repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.3.0  # Latest stable version of Black
    hooks:
      - id: black
        language_version: python3  # Ensure it runs with Python 3

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Latest stable version of Flake8
    hooks:
      - id: flake8
        additional_dependencies: [flake8-django]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [django-stubs]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Latest stable version of isort
    hooks:
      - id: isort

